/* Team Grading tables */

/* Comment Table */
CREATE TABLE Comment(
	ID INTEGER PRIMARY KEY,
	CREATED_TIME TEXT NOT NULL,
	USER_ID INTEGER NOT NULL,
	GRADE_ID INTEGER NOT NULL,
	CONTENT TEXT NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES User(ID),
	FOREIGN KEY(GRADE_ID) REFERENCES Grade(ID)
);

/* Grade Table */
CREATE TABLE Grade(
	ID INTEGER PRIMARY KEY,
	VALUE INTEGER NOT NULL,
	IS_LOCKED BIT DEFAULT 0,
	LAST_MODIFIED TEXT NOT NULL,
	STUDENT_SECTION_ID INTEGER NOT NULL,
	FOREIGN KEY(STUDENT_SECTION_ID) REFERENCES StudentSection(ID)
);

/* Notification Table */
CREATE TABLE Notification(
	ID INTEGER PRIMARY KEY,
	CREATED_TIME TEXT NOT NULL,
	IS_EXPIRED BIT DEFAULT 0,
	MESSAGE TEXT NOT NULL,
	STUDENT_SECTION_ID INTEGER NOT NULL,
	FOREIGN KEY(STUDENT_SECTION_ID) REFERENCES StudentSection(ID)
);