/* Team Facilities Management */

/* Classroom Table */
CREATE TABLE Classroom(
	ID INTEGER PRIMARY KEY,
	PROFESSOR_ID INTEGER,
	CAPACITY INTEGER NOT NULL,
	ROOM_NUM INTEGER NOT NULL,
	BUILDING_NUM INTEGER NOT NULL,
	TERM_ID INTEGER NOT NULL,
	FOREIGN KEY(PROFESSOR_ID) REFERENCES Professor(ID),
	FOREIGN KEY(TERM_ID) REFERENCES Term(ID)
);

/* Reservation Table */
CREATE TABLE Reservation(
	ID INTEGER PRIMARY KEY,
	CLASSROOM_ID INTEGER NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	START_TIME TIME NOT NULL,
	END_TIME TIME NOT NULL,
	IS_ACTIVE BIT DEFAULT 1,
	FOREIGN KEY(CLASSROOM_ID) REFERENCES Classroom(ID)
);

/* Device Table */
CREATE TABLE Device(
	ID INTEGER PRIMARY KEY,
	CLASSROOM_ID INTEGER,
	STUDENT_ID INTEGER,
	IS_RESERVED BIT DEFAULT 0,
	CONDITION TEXT,
	RETURN_DATE DATE,
	FOREIGN KEY(CLASSROOM_ID) REFERENCES Classroom(ID)
	FOREIGN KEY(STUDENT_ID) REFERENCES Student(ID)
);