/* University Human Resources */

/* UniversityEmployee Table */
CREATE TABLE UniversityEmployee(
	ID INTEGER PRIMARY KEY,
	USER_ID INTEGER NOT NULL,
	MANAGER_ID INTEGER NOT NULL,
	TITLE TEXT NOT NULL,
	ADDRESS TEXT NOT NULL,
    PHONE TEXT NOT NULL,
	SALARY REAL NOT NULL,
	IS_TERMINATED BIT DEFAULT 0,
	FOREIGN KEY(USER_ID) REFERENCES User(ID),
	FOREIGN KEY(MANAGER_ID) REFERENCES User(ID)
);
